python3 patch_attack.py \
    --arch resnet18,mobilenet_v2,efficientnet_b0 \
    --loss margin --margin 5.0 \
    --target 80 \
    --guided-init \
    --sequential-ensemble \
    --noise-sigma 0.02 \
    --steps 2000 \
    --oblique-eot \
    --print-cm 8.0 \
    --patch-size 75 \
    --no-fake-quant \
    --eot-samples 4
